### ISSUE TITLE
DRIVER error

### ISSUE THREAD

**Issue by GlauberF** [Alorel/ngforage#100]
**angular 6.x**
**localforage@^1.5.0**
**ngforage@^3.0.0**

In my environment, I was giving error in DRIVE, when it was instantiated and used in the following way:

```
driver: [
          Driver.INDEXED_DB,
          Driver.LOCAL_STORAGE
]
```

![captura de tela de 2018-10-19 10-36-59](https://user-images.githubusercontent.com/11314585/47220778-16b8f300-d389-11e8-9ab2-7729677ea559.png)

changing to this, the error has stopped, but it is not saving in localstorage, only in indexDB
```
driver: [
                'asyncStorage',
                'localStorageWrapper'
            ]
```

**Comment by Alorel** [comment]
`Driver` is only exported in ngforage^4.0.0. Refer to the [old API](https://github.com/Alorel/ngforage/tree/3.4.0#ngforage) for ngforage^3.0.0.

And it will not save to more than one store. See https://localforage.github.io/localForage/#settings-api-setdriver

**Comment by GlauberF** [comment]
@Alorel 
updated to ngforage^4.0.0

![captura de tela de 2018-10-19 11-00-44](https://user-images.githubusercontent.com/11314585/47222164-6a790b80-d38c-11e8-8496-6b8e84c5d210.png)

**Comment by Alorel** [comment]
Hm, what version of Typescript are you using?

**Comment by Alorel** [comment]
Additionally, please create a reproducible example as shown in the [bug report issue template](https://github.com/Alorel/ngforage/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by GlauberF** [comment]
@Alorel 

I updated the angle to 7, typescript too and now it is working.
I have only one doubt:

in my module I'm inserting like this:
```
driver: [
                Driver.INDEXED_DB,
                Driver.LOCAL_STORAGE
]
```

like that in my call to write or save in the specific component which driver to use, example call.

```
public setItem (data) {
        console.log ('Setting value ...');
        try {
            this.ngf.setItem ('email', data.email)
                .then ((d) => {
                    console.log ('Value set!');
                    console.log (d);
                })
        } catch (e) {
            console.log (e);
        }
    }
```


example in this insert I want to send to localstorage

**Comment by Alorel** [comment]
If you want some component to bypass the default priority, you're best off injecting a [DedicatedInstanceFactory](https://alorel.github.io/ngforage/docs/injectables/DedicatedInstanceFactory.html):

```typescript
@Component()
export class FooComponent {
  private readonly ngf: NgForage;

  public constructor(inst: DedicatedInstanceFactory,
                     private readonly standardNgf: NgForage) {
    this.ngf = inst.createNgForage({driver: [Driver.LOCAL_STORAGE]});
  }

  public async setItem(data: any) {
    console.log(`Set to IndexedDB OR localStorage: ${await this.standardNgf.setItem('foo', data)}`);
    console.log(`Set explicitly to localStorage: ${await this.ngf.setItem('bar', data)}`);
  }
}
```

**Comment by GlauberF** [comment]
thanks :)
