### ISSUE TITLE
Docs: What's the difference between NgForage and NgForageCache?

### ISSUE THREAD

**Issue by neobats** [Alorel/ngforage#244]
- [X] I have read the README and API docs (if applicable); the issue is not covered there.
- [X] I have searched the repository issues and pull requests; my query is not covered there.

-----

- **Desired outcome**: I would like additional documentation, or an applicable link to the localforage documentation, to explain the difference between an NgForage store and an NgForageCache store.
- **My attempts**:
  - **On [stackblitz.com](https://stackblitz.com)** (preferred): N/A, but I did dig through the docs and source code.
  - **Git repository** (*only* if a Stackblitz example is not possible): N/A
  
-----

Additional information goes here.
I can't see in the localforage documentation (nor the ngforage documentation) anything about a separate "cache", and want to know what the differences are between NgForage and NgForageCache, if any. If there aren't any differences (I assume there are differences, just don't know what they are), why use one over another?

**Comment by Alorel** [comment]
Hey, sorry for the late reply. NgForage is designed to be just an Angular-formatted version of localforage, whereas NgForageCache is meant to be used as, well, a cache store.

NgForage is best used for permanent storage such as storing a user's preferences, NgForageCache is for more transient data, for example, at work, we've incorporated it into our custom REST client to cache some GET requests:

```typescript
class MyClass {
  public constructor(
    private readonly http: HttpClient,
    private readonly ngf: NgForageCache
  ) {}

  public get(url: string, params?: any): Observable<SomeType> {
    const cacheKey = computeCacheKey(url, params);

    // Check if we have this request cached already
    return from(this.ngf.getCached(cacheKey))
      .pipe(
        switchMap(cachedItem => {
          // Item found in cache and hasn't expired yet
          if (cachedItem.hasData && !cachedItem.expired) {
            return of(cachedItem.data);
          }

          // Item not found - retrieve it
          return this.http.get(url, params).pipe(
            tap(response=> {
              // Cache the response for 5 minutes
              this.ngf.setCached(cacheKey, response, 300000)
                .catch(e => {
                  console.error(`Failed to cache GET ${url}:`, e);
                })
            })
          );
        })
      );
  }
}
```

What it does differently behind the scenes is actually set two keys - if you do `ngForageCache.setCached('myKey', 'someData', someDuration)` it'll set `myKey_data` to `someData` and `myKey_expires` to `Date.now() + someDuration`. NgForageCache also extends the NgForage class so you can just inject the former and do `.setItem()`, `.getItem()` etc calls as you would with a regular NgForage instance. 

Does that clear things up a bit?

**Comment by neobats** [comment]
Yes, actually, that helps a lot! That was a very helpful and descriptive explanation, thank you!

I say this hoping it doesn't put a damper on my thankfulness: it would be really neat to see that kind of description on the documentation. It was really quite a stellar explanation.

**Comment by Alorel** [comment]
Yeah I'll put it in somewhere 🙂 there's an Angular 9 working branch up just now so it'll probably be part of the next release once ng9 is out and stable.
