### ISSUE TITLE
InstanceFactory not available in angular 5

### ISSUE THREAD

**Issue by sreekumarp** [Alorel/ngforage#37]
I am not able to import InstanceFactory so that I can use multiple store instances.

**Comment by Alorel** [comment]
Why would you need to use instance factories directly? The library is tuned to automatically handle instances itself. If you want to use a separate instance of ngForage for some component/service then you should add it to that component's providers, which will create a new ngForage instance

https://github.com/Alorel/ngforage#instance-level-configuration

**Comment by sreekumarp** [comment]
Actually what I am looking for is to configure multiple stores in a DB and access it a single service. What would be the best way you suggesst ?

I am okay with Global Configuration also, if we can do this with it.

**Comment by sreekumarp** [comment]
I think I got it, by setting the storeName property before set and get method.

   ```
    this.ngf.storeName = 'attributesStore';
    return this.ngf.getItem<dcElement>(key.toString());
```

**Comment by Alorel** [comment]
The link I posted above shows the right way to use multiple stores. Make sure you specify the library in the providers for whatever component you're using it in - that way you won't run into any configuration conflicts.

**Comment by sreekumarp** [comment]
I want to use mulitple stores in a service which will be used across application.

Eg. store1, store2, store3 (DB name: applicationDB)

In `common.dataservice.ts` I will use all these 3 services and then this service will be used in different components.

**Comment by zverbeta** [comment]
Hi, you can use useFactory provider for declare different config in different modules, something like this

```
export function forageFactory(config) {
const forageConfig = new NgForageConfig();
return forageConfig.configure(config)
}

{
          provide: NgForageConfig,
          useFactory: forageFactory,
          deps: [YOUR_CONFIG_CLASS]
        }
```
