### ISSUE TITLE
Consider using ng-packagr or something similar to pack the whole project

### ISSUE THREAD

**Issue by PoiScript** [Alorel/ngforage#48]
Right now, the ngforage is not packaged in the right [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview). This causes some terriable problem. For example, ngforage doesn't work in Angular Universal - for more information see https://github.com/angular/angular-cli/issues/7200. I recommend using [ng-packagr](https://github.com/dherges/ng-packagr) to repack the whole project.

**Comment by Alorel** [comment]
Hey - thanks for reporting this. I'm afraid I'll be busy until, propably, the end of the week. If you want this to get done sooner then feel free to open a PR, otherwise it'll be a bit of a wait :slightly_smiling_face:

**Comment by PoiScript** [comment]
Thanks you for your very very quick response XD! Yes, I will try to do that if I can. It should not be any problem.

**Comment by zaalbarxx** [comment]
It would be awesome since the current build does not work properly with angular-cli. Right now it is not possible to build the application using proper version of this library, every build ends up with es2015 version of your package even if my Typescript target is ``es5`` making it broken on IE11. Here is the example repo which causes this problem
``https://github.com/zaalbarxx/angular-ie11test``

**Comment by zaalbarxx** [comment]
I wish I could do that, but well, I am not the one making the calls here, sadly. Looking forward for some fix. Thanks! :)

**Comment by PoiScript** [comment]
I tired to make a pull request but the structure is different from ng-packagr. So I just created a new blank branch at https://github.com/PoiScript/ngforage. I refactored your application with angular-cli also and it worked fine.

But it failed when building the library using `npm run build:lib`. The output:

```
'createInstance' is not exported by 'node_modules/localforage/dist/localforage.js'
'INDEXEDDB' is not exported by 'node_modules/localforage/dist/localforage.js'
'WEBSQL' is not exported by 'node_modules/localforage/dist/localforage.js'
'LOCALSTORAGE' is not exported by 'node_modules/localforage/dist/localforage.js'
'defineDriver' is not exported by 'node_modules/localforage/dist/localforage.js'
'INDEXEDDB' is not exported by 'node_modules/localforage/dist/localforage.js'
'LOCALSTORAGE' is not exported by 'node_modules/localforage/dist/localforage.js'
'WEBSQL' is not exported by 'node_modules/localforage/dist/localforage.js'

BUILD ERROR
ENOENT: no such file or directory, open '/home/poi/projects/ngforage-ng-packagr/node_modules/typescript-lazy-get-decorator/src/LazyGetter.ts'
Error: ENOENT: no such file or directory, open '/home/poi/projects/ngforage-ng-packagr/node_modules/typescript-lazy-get-decorator/src/LazyGetter.ts'
```

I'm not an expert or rollup, but I think the problem is that typescript-lazy-get-decorator was not packaged and exported as UMD. If you have time, you can take a quick look of it :). Maybe modifying some lines in the [package.json](https://github.com/PoiScript/ngforage/blob/ng-packagr/lib/package.json) can make it works.

**Comment by Alorel** [comment]
Thanks for the effort - I'll have a look and repackage the lazy get decorator as UMD as well if needed (didn't have to because it works fine with webpack).

If ngpackagr forces you to use rollup then that may or may not be causing issues since everything here is configured for webpack (I hate rollup with a passion). Anyhoo, we'll get to the bottom of this soon :)

**Comment by Alorel** [comment]
`typescript-lazy-get-decorator` now has a UMD bundle as of [1.1.2](https://www.jsdelivr.com/package/npm/typescript-lazy-get-decorator?path=dist%2Fumd&version=1.1.2) - looking into `ngforage` now

**Comment by PoiScript** [comment]
Sorry for the delay in reply XD. I had read the APF document from cover to cover and it's nothing special but  providing different kinds of bundle to satisfy different kinds of user case. For example, UMD for nodejs environment, esm for Webpack.

ngforage had already provided esm5, esm2015 and umd bundles, so just modify your package.json to something like:
```
"main": "dist/umd/index.js",
"es2015": "dist/esm2015/index.js",
"module": "dist/esm5/index.js",
"typings": "dist/esm2015/index.d.ts",
```
to let optimizers recognize them and anything should just work out of the box :).

**Comment by Alorel** [comment]
If you look at what's actually published to npm, you'll see that this is already present: https://cdn.jsdelivr.net/npm/@ngforage/ngforage-ng5@1.0.5/package.json

Nothing but browser builds should ever really use umd therefore the UMD bundle reference is under the `browser`.

I've used ngforage in my own projects using webpack and it transpiled perfectly.

**Comment by PoiScript** [comment]
In fact, angular universal runs the same client code but in the nodejs, this's why the umd bundle is required. Although angular-cli is now using webpack under the hood, we can not change the webpack config directly. So angular-cli will always try to use the main field bundle when doing server-side rendering and causes syntax error(using `import` statement in nodejs).

If you're still confusing, I can provide a minimal repo for reproducing it.

**Comment by Alorel** [comment]
That's interesting given how both the lazy get decorator and ngforage have their `main` fields point to the CommonJS ES5 build which does not have any import statements. I have a little bit more time this week so I'll try experimenting with this a bit. If setting `main` to the UMD build within `node_modules` does the trick when packaging I might have the new version up either today or tomorrow.

**Comment by Alorel** [comment]
Better late than never!

I've published the library under its old name, `ngforage`. Install version `^2.0.0` for Angular 5 or `^3.0.0` for Angular 6.

It's now packaged with `ng-packagr` and has some new features - see the changelog for details. :slightly_smiling_face:

**Comment by PoiScript** [comment]
Greate, thank you! Updating this package right now.

**Comment by PoiScript** [comment]
Well, it looks like that we need to install `localforage` separately when using the `ngforage` package. Because `localforage` is the peerDependencies of `ngforage`. If so, maybe you should update the installaion document.

**Comment by Alorel** [comment]
Oh, I completely missed that - sorry! Will update in a second.
