### ISSUE TITLE
Angular 16 Support

### ISSUE THREAD

**Issue by layinka** [Alorel/ngforage#523]
- [x ] I have read the README and API docs (if applicable); the issue is not covered there.
- [x ] I have searched the repository issues and pull requests; my query is not covered there.

-----

- **Describe the feature**: 
Great work on this project.
Any plans for supporting Angular 16?

**Comment by codepearlex** [comment]
I'd be interested, too. Of all the dependencies my project has, `ngforage` is the last one without Angular 16 support.

**Comment by JoaoEdu93** [comment]
I'm interested too. Thanks.

**Comment by Alorel** [comment]
Sorry for the delay, troops, it's now been published
