### ISSUE TITLE
How to create multiple stores?

### ISSUE THREAD

**Issue by benson-jala** [Alorel/ngforage#53]
localforage.createInstance() will create store instance using localforage
how to create with localforage-ng5.

**Comment by Alorel** [comment]
Hey. ngforage automatically handles this internally - it checks the configuration hash before every operation and calls `localforage.createInstance()` if the hash has changed.

At the moment, this is roughly how things work:

```ts
class MyComponent implements OnInit {
   private readonly ngf: NgForage;

   public ngOnInit(): void {
      this.ngf.name = 'foo'; // creates a store with the name 'foo';
   }

   public someMethod(): void {
      this.ngf.getItem('a'); // Gets an item from store 'foo';
      this.ngf.name = 'bar'; // creates a store called 'bar';
      this.ngf.getItem('b'); // Gets an item from store 'foo';
      this.nfg.name = 'foo'; // Switches back to store 'foo', reuses existing store.
      this.ngf.getItem('c'); // Gets an item from store 'foo';
   }
}
```

For components you could simply add it to the providers, which would create a component-specific instance of ngforage:

```ts
@Component({
   providers: [NgForage]
});
```

Such an approach does not currently exist for injectables and will be added in a future release; unfortunately, I don't know when I'll have time to implement it.

**Comment by benson-jala** [comment]
Thank you for timely response.

**Comment by Dedme** [comment]
Hello, i am looking to use multiple named stores in services across my application, so this is in Injectables.
Is there a way i am able to manually configure something if the DC isn't there yet?

**Comment by Dedme** [comment]
Just wanted to close this out with that i solved this current by using the clone functionality.

in my service i am importing the defualt NGForage instance.

```javascript
private ngf: NgForage;
constructor(ngfd: NgForage) {
  this.ngf = ngfd.clone({storeName: 'newName'});
}
```

**Comment by Alorel** [comment]
@Dedme You could also use the dedicated instance factory: https://alorel.github.io/ngforage/docs/injectables/DedicatedInstanceFactory.html

**Comment by Alorel** [comment]
@Dedme Inject it like anything else...

```typescript
import { DedicatedInstanceFactory, NgForage } from 'ngforage';
import { Injectable } from '@angular/core';

@Injectable({providedIn: 'root'})
export class MyService {
    private readonly ngForage1: NgForage;
    private readonly ngForage2: NgForage;

	public constructor(dif: DedicatedInstanceFactory) {
		this.ngForage1 = dif.createNgForage({name: 'foo'});
		this.ngForage2 = dif.createNgForage({name: 'RTFM'});
	}
}
```
