### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by codepearlex** [Alorel/ngforage#568]
- [x] I have read the README and API docs (if applicable); the issue is not covered there.
- [x] I have searched the repository issues and pull requests; my query is not covered there.

-----

- **Describe the feature**: Support for Angular 17
- [ ] I would be able to implement this feature and make a pull request.
  
-----

Thanks for your work on the project! Angular 17 support would be awesome.

**Comment by Alorel** [comment]
Hey. I'm afraid I have basically no capacity in the near future - a PR would be appreciated and, afterwards, I believe I'll be putting the repo in an archived state - I haven't used it personally or at work since Angular 14 or 15 and that only leads to `ngforage` updates coming in very late.

**Comment by niconaso** [comment]
Hi @codepearlex @Alorel I just created a PR to support Angular 17 -> https://github.com/Alorel/ngforage/pull/571

**Comment by niconaso** [comment]
Hi! Have you been able to review the PR?

**Comment by Alorel** [comment]
Merged and released, cheers.
