### ISSUE TITLE
No available storage method found - Angular and Universal

### ISSUE THREAD

**Issue by patrykp57** [Alorel/ngforage#66]
Hello, currently I'm using NgForage 2.0.4 and LocalForage 1.7.1 with Angular 5.2.10 and Angular Universal, and sometimes when I'm navigating throught pages I'm getting error like :

```
ERROR { Error: Uncaught (in promise): Error: No available storage method found.
Error: No available storage method found.
```
I'm using NgForage to hold data for offline PWA. To download data from API (or from IndexeDB) I wrote two functions - one for browser side (with NgForage) and one for server side (without NgForage). It's looks like : 

```
    if (isPlatformBrowser(this.platformId)) {
      this.getDataFromIndexedDB(params, index);
    }

    if (isPlatformServer(this.platformId))
      this.getDataFromApi(params, index);
```

So error visible above shouldn't even appear. I read it's only showing when LocalForage can't find window.promise, but in my sytuation, window.promise always exist. On server side I'm not using NgForage. Do you know how to fix that ? Error only appear in production version and linking to this part of LocalForage: 

```
   this._driverSet = oldDriverSetDone.then(function () {
            var driverName = supportedDrivers[0];
            self._dbInfo = null;
            self._ready = null;

            return self.getDriver(driverName).then(function (driver) {
                self._driver = driver._driver;
                setDriverToConfig();
                self._wrapLibraryMethodsWithReady();
                self._initDriver = initDriver(supportedDrivers);
            });
        })["catch"](function () {
            setDriverToConfig();
            var error = new Error('No available storage method found.');
            self._driverSet = Promise$1.reject(error);
            return self._driverSet;
        });
```

**Comment by Alorel** [comment]
Hey. I only developed the Angular wrapper, not localForage, so I'm not sure what's going on in the bottom snippet.

I'm using the same Angular and localForage versions at work and am not having any issues, so, by the looks of it, there's a problem with your setup (and I won't have time to look into it this weekend).

The error itself implies that whatever driver or array of drivers were being set, it is/they are not supported by the environment (e.g. localStorage is not available when the driver is set to localStorage).

The best I can suggest for now is is inspecting exactly what's being passed down the call stack - either by adding a bunch of log statements or by adding breakpoints in Chrome's sources tab.

**Comment by patrykp57** [comment]
Nevermind. I had a little problem in API. There was PHP error. So when I was calling HTTP GET like that 

```
    this.http.getResponseAsync(`${this.URL}/api/menu/${lang}`).then(async (data: Menu) => {
      if (await data)
        this.menu = data;
    }, (error) => {
      console.log(error);
      this.dl.getMenu(this.config.impressURL, this.langUrl).then(async (response: any) => {
        this.menu = await response;
      });
    });
```

On server side getMenu from IndexedDB were calling.
